services:
  ollama:
    restart: always
    image: whatwewant/ollama:${SERVICE_OLLAMA_IMAGE_VERSION}
    # ports:
    #   - 0.0.0.0:${SERVICE_OLLAMA_PORT}:11434
    volumes:
      - ${SERVICE_DATA}:/root/.ollama
      
networks:
  default:
    external: true
    name: compose-ingress
